# Generated by Django 5.1.3 on 2024-11-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnjoyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', verbose_name='Название развлечения')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Изображение развлечения')),
                ('price', models.TextField(default='', verbose_name='Цена за развлечения')),
                ('description', models.TextField(default='', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Развлечение',
                'verbose_name_plural': 'Развлечения',
            },
        ),
    ]
