# Generated by Django 5.1.3 on 2024-11-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_housemodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemodel',
            name='price_on_card',
            field=models.TextField(default='', verbose_name='Цена на карточке'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='price',
            field=models.TextField(default='', verbose_name='Цена в карточке'),
        ),
    ]
