# Generated by Django 5.1.3 on 2024-11-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicemodel',
            old_name='image',
            new_name='photo',
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='price_on_card',
            field=models.TextField(default='', verbose_name='Цена на карточке'),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='price',
            field=models.TextField(default='', verbose_name='Цена в карточке'),
        ),
    ]
